kind: Service
apiVersion: v1
metadata:
  namespace: frontend
  name: car-app-svc
spec:
  type: NodePort
  selector:
    app: car-app
  ports:
    - name: car-app
      port: 3000
      targetPort: 3000 
      
