apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference the base kustomization
resources:
- ../../base
- ../../../pkg/pkg2/manifests/postgres-configmap.yaml
- ../../../pkg/pkg2/manifests/postgres-secret.yaml
- ../../../pkg/pkg3/manifests/ingress.yaml

# Patch common labels for this environment
commonLabels:
  environment: staging

# Configure replicas for staging
patches:
- target:
    kind: Deployment
    name: .*
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2
