kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: april
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 31235
    hostPort: 31235
  - containerPort: 31613
    hostPort: 31613
- role: worker
- role: worker
networking:
  disableDefaultCNI: false

