kind: Service
apiVersion: v1
metadata:
  labels:
    app: car-app-svc
  namespace: frontend
  name: car-app-svc
spec:
  type: NodePort
  selector:
    app: car-app
  ports:
    - name: car-app
      port: 3000        # Expose the service on port 3000 within the cluster
      targetPort: 3000   # The container inside the pod listens on port 3000
      nodePort: 30001    # Expose the service externally on port 30001
      
