# ./kustomize/overlays/dev/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: frontend-dev

labels:
- includeSelectors: true
  pairs:
    app: car-app
    environment: production

patches:
- path: patches/deploy.yaml