apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    name: myapp
spec:
  serviceAccountName: alvo-svc
  containers: 
  - name: myapp
    image: alvin254/car-app:v1.0.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
