apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
subjects:
- kind: ServiceAccount
  name: alvo-svc
  namespace: rbac-example
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io


---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-list-pods
  namespace: rbac-example
subjects:
- kind: ServiceAccount
  name: alvo-svc
  namespace: rbac-example
roleRef:
  kind: ClusterRole
  name: list-pods
  apiGroup: rbac.authorization.k8s.io
