apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-only-binding
subjects:
- kind: ServiceAccount
  name: alvo-svc
  namespace: rbac-example
roleRef:
  kind: Role
  name: read-only
  apiGroup: rbac.authorization.k8s.io



