apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common resources across all environments
resources:
- manifests/deployment.yaml
- manifests/service-account.yaml
- manifests/car-service.yaml



# Common labels to be applied to all resources
labels:
- includeSelectors: true
  pairs:
    app: car-app
    environment: base
